import { createClient } from '@supabase/supabase-js';

// --- DATABASE SETUP INSTRUCTIONS ---
// 1. Create a project at https://supabase.com
// 2. Go to the SQL Editor and run the following queries:
/*
  -- Create Projects Table
  create table projects (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    title text,
    category text,
    description text,
    tools text[],
    behance text,
    youtube text,
    image text,
    likes bigint default 0
  );

  -- IF YOU ALREADY HAVE THE TABLE, RUN THIS TO ADD THE COLUMN:
  -- alter table projects add column youtube text;

  -- Enable Row Level Security (RLS)
  alter table projects enable row level security;

  -- Create Policy: Everyone can view projects
  create policy "Public projects are viewable by everyone"
  on projects for select
  to public
  using (true);

  -- Create Policy: Everyone can insert/update (For demo purposes - secure this in production!)
  create policy "Anyone can insert projects"
  on projects for insert
  to public
  with check (true);

  create policy "Anyone can update projects"
  on projects for update
  to public
  using (true);
  
  create policy "Anyone can delete projects"
  on projects for delete
  to public
  using (true);

  -- Create Storage Bucket for Images
  insert into storage.buckets (id, name, public) values ('portfolio-images', 'portfolio-images', true);
  
  -- Storage Policy
  create policy "Public Access"
  on storage.objects for select
  using ( bucket_id = 'portfolio-images' );
  
  create policy "Public Upload"
  on storage.objects for insert
  with check ( bucket_id = 'portfolio-images' );
*/

// Retrieve environment variables
// Note: In Vite, we use import.meta.env
const supabaseUrl = (import.meta as any).env.VITE_SUPABASE_URL;
const supabaseKey = (import.meta as any).env.VITE_SUPABASE_ANON_KEY;

// Check if variables are set to their actual values (not undefined and not placeholders)
const isConfigured = 
  supabaseUrl && 
  supabaseKey && 
  supabaseUrl !== 'https://your-project.supabase.co';

// Create the client
// We provide fallbacks to prevent the app from crashing immediately on load,
// but API calls will fail if not configured.
export const supabase = createClient(
  supabaseUrl || 'https://your-project.supabase.co', 
  supabaseKey || 'your-anon-key'
);

// Helper to validate configuration before performing actions
export const checkSupabaseConfig = () => {
  if (!isConfigured) {
    throw new Error(
      'Supabase is not configured properly. Please add VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY to your Netlify Site Settings (Environment Variables).'
    );
  }
};